### ISSUE TITLE
Проблемы с аватаром

### ISSUE THREAD

**Issue by RafRaf** [djbook-ru/djbookru#109]
На самом деле эта проблема делится на несколько:
1. При смене своего аватара через gravatar.com в профиле изображение не меняется (остается старая авто-сгенерированная картинка), хотя на форуме корректно отображается мой новый аватар.
2. В профиле же сама картинка должна быть ссылкой на профиль в стиле http://gravatar.com/89yrhwer3incsdif . Если вы заметили никто кроме модераторов форума не "носит аватаров" т.к. не интуитивно понятно как сменить свой аватар.
3. Checkbox "использовать аватар" (в профиле же) должна быть всегда снята, так как загрузки своих изображений на сайт не предусмотрено + она должна быть скрыта так как на сайте используется только gravatar.ru.

**Comment by RomanMarinov** [comment]
просто выйти и зайти заново в акк, и все поменяется

**Comment by plamer777** [comment]
Такая же проблема. Не отключить и не поменять.

**Comment by Kolonin-Gleb** [comment]
Проблема по прежнему есть
