### ISSUE TITLE
Сообщения пользователю через message-фреймверк

### ISSUE THREAD

**Issue by Alerion** [djbook-ru/djbookru#11]
В 1.2 обновили message фреймверк. Очень привлекательная штука получилась. Добавить его использование для вь.х, обрабатывающих формы. Вот пример: http://github.com/RaD/djbookru/blob/master/src/accounts/views.py#L22
Дизайн добавил для сообщений success и error. Можно использовать и другие.

**Comment by den-is** [comment]
нег
